name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  workflow_dispatch:
#   push:
#     branches: [ main, dev ]
#     paths: src/**
#   pull_request:
#     branches: [ main ]
#     paths: src/**
  # Only trigger, when the build workflow succeeded
#   workflow_run:
#     workflows: ["Build / Test (with Reports)"]
#     types:
#       - completed

# permissions:
#   contents: read
#   issues: read
#   checks: write
#   pull-requests: write
#   pages: write
#   id-token: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    
#     defaults:
#       run:
#         working-directory: src/Poker/Poker.WebApp
    
#     if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET 7.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish src/Poker/Poker.WebApp/Poker.WebApp.csproj -c Release -o release --nologo
    
    # changes the base-tag in index.html from '/' to 'Utility' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to Poker WebApp
      run: sed -i 's/<base href="\/" \/>/<base href="\/poker-recording\/" \/>/g' release/wwwroot/index.html
    
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.6.0
      with:
        branch: gh-pages
        folder: release/wwwroot
